### ISSUE TITLE
WEBPAGE: Move useful parts from meteor-application-template-react into DAAJ repo

### ISSUE THREAD

**Issue by mujtaba-a-quadri** [HACC2021/DAAJ#9]
From meteor-application-template-react/app/imports/ui

make sure to have the necessary packages imported/available

**Comment by alyssia-chen** [comment]
We may also need some stuff from other folders in the imports folder now that I think about it.
https://github.com/ics-software-engineering/meteor-application-template-react/tree/master/app/imports

Like the Accounts.js and maybe here's where we can do the startup data of like one admin user?? There might be a better area to do this
